// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kfkudweokccaediisitr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtma3Vkd2Vva2NjYWVkaWlzaXRyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI1OTAwNDMsImV4cCI6MjA2ODE2NjA0M30.aH-PctxiYZaTo1EQG7KGu5bUPILDGUwFbQS5Wof1GC8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});